name: rent
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.0.0

  flutter_bloc: ^9.1.1
  bloc: ^9.0.0

  flutter_localizations:
    sdk: flutter

  http: ^1.6.0
  dio: ^5.9.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  uuid: ^4.5.2
  flutter_riverpod: ^3.1.0

  intl: ^0.20.2

  flutter_secure_storage: ^10.0.0

  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

  fonts:
    - family: Playfair Display
      fonts:
        - asset: fonts/PlayfairDisplay-VariableFont_wght.ttf

    - family: DM Serif Display
      fonts:
        - asset: fonts/DMSerifDisplay-Regular.ttf
