name: rent
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4

  # state management
  flutter_bloc: ^9.1.1

  # networking (شغل زميلك)
  http: ^1.6.0
  dio: ^5.9.0

  # utils
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Playfair Display
      fonts:
        - asset: fonts/PlayfairDisplay-VariableFont_wght.ttf

    - family: DM Serif Display
      fonts:
        - asset: fonts/DMSerifDisplay-Regular.ttf
